# Generated by Django 4.0.6 on 2022-08-22 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMst',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('campaignname', models.CharField(db_column='Campaign Name', default='', max_length=200)),
                ('sdate', models.DateField(db_column='Start Date', null=True)),
                ('stime', models.TimeField(db_column='Start Time', null=True)),
                ('edate', models.DateField(db_column='End Date', null=True)),
                ('etime', models.TimeField(db_column='End Time', null=True)),
                ('location', models.CharField(db_column='Location', default='', max_length=30)),
                ('city', models.CharField(db_column='City', default='', max_length=30)),
            ],
            options={
                'db_table': 'Campaign Master',
            },
        ),
        migrations.CreateModel(
            name='CampaignSumary',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cdate', models.DateField(db_column='Campaign Date', null=True)),
                ('location', models.CharField(db_column='Location', max_length=50, null=True)),
                ('noofdoners', models.IntegerField(db_column='NoOf Doners', default=0)),
                ('bloodgroup', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-')], db_column='Blood Group', default='A', max_length=3)),
            ],
            options={
                'db_table': 'Campaign Sumary',
            },
        ),
        migrations.CreateModel(
            name='StateCityMaster',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_column='State', max_length=3, null=True)),
                ('city_name', models.CharField(db_column='City', max_length=40, null=True)),
                ('zipcode', models.CharField(db_column='ZipCode', max_length=6, null=True)),
            ],
            options={
                'db_table': 'StateCity Master',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profileid', models.AutoField(db_column='Profile ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=30)),
                ('last_name', models.CharField(db_column='Last Name', max_length=30)),
                ('bloodgroup', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-')], db_column='Blood Group', default='B+', max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], db_column='Gender', default='M', max_length=1)),
                ('dob', models.DateField(db_column='Date of Birth')),
                ('mobileno', models.IntegerField(db_column='Mobile Number')),
                ('email', models.EmailField(db_column='EMail', max_length=50)),
                ('subs', models.BooleanField(db_column='Subscription', default=False)),
                ('address1', models.CharField(db_column='Address1', max_length=300)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=300, null=True)),
                ('zipcode', models.CharField(db_column='Zip Code', max_length=6)),
                ('state', models.CharField(db_column='State', max_length=10)),
                ('city', models.CharField(db_column='City', max_length=20)),
                ('userid', models.OneToOneField(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='DonnerSumary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastdateDonation', models.DateField(db_column='Last DonationDate', null=True)),
                ('noofunits', models.IntegerField(db_column='Units', null=True)),
                ('threshhold', models.IntegerField(db_column='ThreshHold Value', null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Donner Summary',
            },
        ),
        migrations.CreateModel(
            name='CampaignDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.CharField(db_column='Guest Name', default='', max_length=100)),
                ('mobileno', models.CharField(db_column='Mobile Number', default='', max_length=10)),
                ('email', models.EmailField(db_column='Email', default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], db_column='Gender', default='M', max_length=1)),
                ('age', models.IntegerField(db_column='Age', default=18)),
                ('bloodgroup', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-')], db_column='Blood Group', default='A', max_length=3)),
                ('cid', models.ForeignKey(db_column='ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bldapp.campaignmst')),
            ],
            options={
                'db_table': 'Campaign Details',
            },
        ),
        migrations.CreateModel(
            name='BloodDonerTransactions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('donationdatetime', models.DateTimeField(db_column='Donation DTime', null=True)),
                ('units', models.IntegerField(db_column='Units', default=0)),
                ('shelflife', models.IntegerField(db_column='Shelf Life', default=2)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BlDoner Trans',
            },
        ),
    ]
