# Generated by Django 4.0.6 on 2022-08-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bloodgroup',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-')], db_column='Blood Group', default='B+', help_text='Select Blood Group', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(db_column='Date of Birth', help_text='Enter / Select Date of Birth (YYYY-MM-DD)', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(db_column='First Name', help_text='Enter First Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], db_column='Gender', default='M', help_text='Select Gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(db_column='Last Name', help_text='Enter Last Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobileno',
            field=models.CharField(db_column='Mobile Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subs',
            field=models.BooleanField(db_column='Subscription', default=False, verbose_name='Subscribe ? '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.OneToOneField(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
    ]
