# Generated by Django 4.1 on 2022-09-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldapp', '0003_remove_blooddonertransactions_donationdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecitymaster',
            name='state_name',
            field=models.CharField(db_column='State Name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='statecitymaster',
            name='state_code',
            field=models.CharField(db_column='State Code', max_length=3, null=True),
        ),
    ]
